import {
  UserProfile,
  Tenant,
  Batch,
  Student,
  TimetableSlot,
  AttendanceRecord,
  LMSLesson,
  Assignment,
  ExamResult,
  LeaveRequest,
  Notice,
} from './types';

export const mockTenant: Tenant = {
  id: 'tenant-apex-01',
  name: 'Apex Institute of Science',
  subdomain: 'apex',
  institutionType: 'coaching',
  primaryColor: '#4F46E5', // Indigo
  secondaryColor: '#06B6D4', // Cyan
  accentColor: '#F59E0B', // Amber
  tagline: 'Empowering Future IITians & Doctors',
  logoUrl: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=120&auto=format&fit=crop&q=80',
};

export const mockProfiles: Record<string, UserProfile> = {
  student: {
    id: 'user-std-01',
    email: 'aarav.sharma@apexacademy.in',
    firstName: 'Aarav',
    lastName: 'Sharma',
    role: 'student',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    phone: '+91 98765 43210',
    tenantId: mockTenant.id,
    branchId: 'branch-ahmedabad',
  },
  teacher: {
    id: 'user-tch-01',
    email: 'amit.verma@apexacademy.in',
    firstName: 'Prof. Amit',
    lastName: 'Verma',
    role: 'teacher',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    phone: '+91 98234 56789',
    tenantId: mockTenant.id,
    branchId: 'branch-ahmedabad',
  },
  principal: {
    id: 'user-prn-01',
    email: 'rajesh.iyer@apexacademy.in',
    firstName: 'Dr. Rajesh',
    lastName: 'Iyer',
    role: 'principal',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    phone: '+91 99887 66554',
    tenantId: mockTenant.id,
    branchId: 'branch-ahmedabad',
  },
  parent: {
    id: 'user-par-01',
    email: 'rajesh.sharma.parent@gmail.com',
    firstName: 'Mr. Rajesh',
    lastName: 'Sharma',
    role: 'parent',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    phone: '+91 98111 22334',
    tenantId: mockTenant.id,
    branchId: 'branch-ahmedabad',
  },
  super_admin: {
    id: 'user-adm-01',
    email: 'admin@eduos.app',
    firstName: 'EduOS',
    lastName: 'SuperAdmin',
    role: 'super_admin',
    avatarUrl: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=80',
    phone: '+91 90000 00001',
    tenantId: mockTenant.id,
  },
};

export const mockBatches: Batch[] = [
  {
    id: 'batch-jee-11a',
    name: 'Class 11 - JEE Advanced Alpha',
    code: 'JEE-11A',
    targetExam: 'JEE Advanced 2027',
    gradeLevel: 'Class 11',
    roomNumber: 'Hall 101',
    mentorTeacherName: 'Prof. Amit Verma',
    studentCount: 38,
    capacity: 40,
  },
  {
    id: 'batch-neet-12b',
    name: 'Class 12 - NEET Medical Champions',
    code: 'NEET-12B',
    targetExam: 'NEET UG 2026',
    gradeLevel: 'Class 12',
    roomNumber: 'Hall 204',
    mentorTeacherName: 'Dr. Sunita Rao',
    studentCount: 42,
    capacity: 45,
  },
  {
    id: 'batch-found-10',
    name: 'Class 10 - Olympiad & Foundation',
    code: 'FND-10',
    targetExam: 'NTSE / Olympiads',
    gradeLevel: 'Class 10',
    roomNumber: 'Room 302',
    mentorTeacherName: 'Prof. Vikram Roy',
    studentCount: 30,
    capacity: 35,
  },
];

export const mockCurrentStudent: Student = {
  id: 'std-aarav-01',
  userId: 'user-std-01',
  name: 'Aarav Sharma',
  email: 'aarav.sharma@apexacademy.in',
  rollNumber: 'APX-2026-1104',
  admissionNumber: 'ADM-9842',
  batchId: 'batch-jee-11a',
  batchName: 'Class 11 - JEE Advanced Alpha',
  targetExam: 'JEE Advanced 2027',
  attendancePct: 94.2,
  rankInBatch: 3,
  parentName: 'Mr. Rajesh & Mrs. Sunita Sharma',
  parentPhone: '+91 98111 22334',
  qrCodeId: 'APX-QR-88392-AARAV',
  avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
};

export const mockStudentsInBatch: Student[] = [
  mockCurrentStudent,
  {
    id: 'std-02',
    userId: 'user-02',
    name: 'Rohan Gupta',
    email: 'rohan.g@apexacademy.in',
    rollNumber: 'APX-2026-1105',
    admissionNumber: 'ADM-9843',
    batchId: 'batch-jee-11a',
    batchName: 'Class 11 - JEE Advanced Alpha',
    targetExam: 'JEE Advanced 2027',
    attendancePct: 89.5,
    rankInBatch: 7,
    parentName: 'Sanjay Gupta',
    parentPhone: '+91 98111 22335',
    qrCodeId: 'APX-QR-88393-ROHAN',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'std-03',
    userId: 'user-03',
    name: 'Ananya Deshmukh',
    email: 'ananya.d@apexacademy.in',
    rollNumber: 'APX-2026-1106',
    admissionNumber: 'ADM-9844',
    batchId: 'batch-jee-11a',
    batchName: 'Class 11 - JEE Advanced Alpha',
    targetExam: 'JEE Advanced 2027',
    attendancePct: 98.0,
    rankInBatch: 1,
    parentName: 'Vivek Deshmukh',
    parentPhone: '+91 98111 22336',
    qrCodeId: 'APX-QR-88394-ANANYA',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'std-04',
    userId: 'user-04',
    name: 'Karan Mehra',
    email: 'karan.m@apexacademy.in',
    rollNumber: 'APX-2026-1107',
    admissionNumber: 'ADM-9845',
    batchId: 'batch-jee-11a',
    batchName: 'Class 11 - JEE Advanced Alpha',
    targetExam: 'JEE Advanced 2027',
    attendancePct: 76.4,
    rankInBatch: 22,
    parentName: 'Ashok Mehra',
    parentPhone: '+91 98111 22337',
    qrCodeId: 'APX-QR-88395-KARAN',
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'std-05',
    userId: 'user-05',
    name: 'Pooja Iyer',
    email: 'pooja.i@apexacademy.in',
    rollNumber: 'APX-2026-1108',
    admissionNumber: 'ADM-9846',
    batchId: 'batch-jee-11a',
    batchName: 'Class 11 - JEE Advanced Alpha',
    targetExam: 'JEE Advanced 2027',
    attendancePct: 92.1,
    rankInBatch: 5,
    parentName: 'Ramesh Iyer',
    parentPhone: '+91 98111 22338',
    qrCodeId: 'APX-QR-88396-POOJA',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
  },
];

export const mockTimetable: TimetableSlot[] = [
  {
    id: 'tt-1',
    dayOfWeek: 1, // Monday
    periodNumber: 1,
    startTime: '08:30 AM',
    endTime: '10:00 AM',
    subjectName: 'Physics (Mechanics & Rotational)',
    subjectColor: '#4F46E5',
    teacherName: 'Prof. Amit Verma',
    roomNumber: 'Hall 101',
    batchId: 'batch-jee-11a',
  },
  {
    id: 'tt-2',
    dayOfWeek: 1,
    periodNumber: 2,
    startTime: '10:15 AM',
    endTime: '11:45 AM',
    subjectName: 'Physical Chemistry (Thermodynamics)',
    subjectColor: '#06B6D4',
    teacherName: 'Dr. Sunita Rao',
    roomNumber: 'Hall 101',
    batchId: 'batch-jee-11a',
  },
  {
    id: 'tt-3',
    dayOfWeek: 1,
    periodNumber: 3,
    startTime: '12:30 PM',
    endTime: '02:00 PM',
    subjectName: 'Mathematics (Calculus & Functions)',
    subjectColor: '#10B981',
    teacherName: 'Prof. Vikram Roy',
    roomNumber: 'Hall 101',
    batchId: 'batch-jee-11a',
  },
  {
    id: 'tt-4',
    dayOfWeek: 1,
    periodNumber: 4,
    startTime: '02:15 PM',
    endTime: '03:45 PM',
    subjectName: 'JEE Advanced Problem Solving Session',
    subjectColor: '#F59E0B',
    teacherName: 'Prof. Amit Verma',
    roomNumber: 'Lab 2',
    batchId: 'batch-jee-11a',
  },
];

export const mockLMSLessons: LMSLesson[] = [
  {
    id: 'lms-1',
    courseTitle: 'Physics: Rotational Dynamics',
    chapter: 'Chapter 05: Moment of Inertia & Torque',
    title: 'Lecture 04: Conservation of Angular Momentum & Rolling without Slipping',
    contentType: 'video',
    durationMinutes: 52,
    url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    completed: true,
  },
  {
    id: 'lms-2',
    courseTitle: 'Physics: Rotational Dynamics',
    chapter: 'Chapter 05: Moment of Inertia & Torque',
    title: 'Daily Practice Problem (DPP-12) & Detailed Solutions',
    contentType: 'pdf',
    durationMinutes: 30,
    completed: true,
  },
  {
    id: 'lms-3',
    courseTitle: 'Mathematics: Integral Calculus',
    chapter: 'Chapter 03: Definite Integration by Substitution',
    title: 'Lecture 02: King Property & Leibnitz Integral Rule',
    contentType: 'video',
    durationMinutes: 65,
    completed: false,
  },
  {
    id: 'lms-4',
    courseTitle: 'Organic Chemistry: Reaction Mechanisms',
    chapter: 'Chapter 04: Electrophilic Aromatic Substitution',
    title: 'Condensed Formula Sheet & High-Yield Reaction Flowchart',
    contentType: 'notes',
    durationMinutes: 20,
    completed: false,
  },
];

export const mockAssignments: Assignment[] = [
  {
    id: 'asg-01',
    title: 'Physics DPP-14: Work-Energy & Variable Forces',
    subject: 'Physics',
    batchName: 'Class 11 - JEE Advanced Alpha',
    dueDate: 'Tomorrow, 11:59 PM',
    maxMarks: 40,
    status: 'pending',
  },
  {
    id: 'asg-02',
    title: 'Maths Advanced Worksheet: Continuity & Differentiability',
    subject: 'Mathematics',
    batchName: 'Class 11 - JEE Advanced Alpha',
    dueDate: '20 Aug 2026',
    maxMarks: 50,
    status: 'submitted',
  },
  {
    id: 'asg-03',
    title: 'Chemistry Quiz: Gaseous State & Real Gas Equations',
    subject: 'Chemistry',
    batchName: 'Class 11 - JEE Advanced Alpha',
    dueDate: '15 Aug 2026',
    maxMarks: 30,
    status: 'graded',
    obtainedMarks: 28,
    feedback: 'Excellent conceptual clarity on Van der Waals parameters!',
  },
];

export const mockExamResults: ExamResult[] = [
  {
    id: 'ex-01',
    examTitle: 'All-India Major Mock Test 03 (Paper 1 + 2)',
    subject: 'Full JEE Advanced (PCM)',
    examDate: '12 Aug 2026',
    marksObtained: 248,
    totalMarks: 360,
    percentile: 98.45,
    rankInBatch: 3,
    weakTopics: ['Rotational Collision Problems', 'Thermodynamic Cycles P-V Graphs'],
    mistakeSummary: 'Strong in Calculus (92%) and Inorganic. 3 calculation slips in Physics application questions.',
  },
  {
    id: 'ex-02',
    examTitle: 'Unit Test 04: Mechanics & Vector Calculus',
    subject: 'Physics & Maths',
    examDate: '28 Jul 2026',
    marksObtained: 92,
    totalMarks: 100,
    percentile: 99.1,
    rankInBatch: 2,
    weakTopics: ['Friction on Incline Double Blocks'],
    mistakeSummary: 'Very high accuracy. 1 question missed due to time pressure.',
  },
];

export const mockNotices: Notice[] = [
  {
    id: 'not-01',
    title: 'All-India JEE Advanced Mock Test Series 04 Announced',
    content: 'The next offline CBT mock test will be conducted this Sunday from 09:00 AM to 12:00 PM (Paper 1) and 02:30 PM to 05:30 PM (Paper 2). Hall tickets available for download.',
    category: 'exam',
    date: '18 Aug 2026',
    author: 'Academic Directorate',
  },
  {
    id: 'not-02',
    title: 'Special Doubt-Clearing Workshop for Thermodynamics',
    content: 'Prof. Amit Verma will be conducting a 3-hour marathon problem-solving clinic for Class 11 JEE batches on Saturday at 04:00 PM in Lab 1.',
    category: 'academic',
    date: '17 Aug 2026',
    author: 'Prof. Amit Verma',
  },
  {
    id: 'not-03',
    title: 'Independence Day Holiday & Schedule Notice',
    content: 'Classes will remain suspended on 15th August. Regular timetable resumes on 16th August at 08:30 AM.',
    category: 'event',
    date: '14 Aug 2026',
    author: 'Principal Office',
  },
];

export const mockLeaveRequests: LeaveRequest[] = [
  {
    id: 'lr-01',
    employeeName: 'Prof. Vikram Roy',
    designation: 'Senior Faculty - Mathematics',
    leaveType: 'Casual Leave',
    startDate: '22 Aug 2026',
    endDate: '23 Aug 2026',
    reason: 'Attending National Mathematics Olympiad Council meeting in Delhi.',
    status: 'pending',
    appliedAt: 'Today, 10:15 AM',
  },
  {
    id: 'lr-02',
    employeeName: 'Dr. Sunita Rao',
    designation: 'Faculty - Chemistry',
    leaveType: 'Medical Leave',
    startDate: '10 Aug 2026',
    endDate: '11 Aug 2026',
    reason: 'Dental surgery and recovery.',
    status: 'approved',
    appliedAt: '09 Aug 2026',
  },
];

export const mockParentChildren = [
  {
    id: 'child-01',
    name: 'Aarav Sharma',
    grade: 'Class 11 - JEE Advanced Alpha',
    rollNumber: 'APX-2026-1104',
    branch: 'Ahmedabad Main Campus',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    attendance: 94.2,
    latestScore: '248/360 (98.45%ile)',
    feeStatus: 'Term 2 Due: ₹45,000',
    targetExam: 'JEE Advanced 2027',
  },
  {
    id: 'child-02',
    name: 'Ananya Sharma',
    grade: 'Class 8 - Foundation & Olympiad',
    rollNumber: 'APX-2026-0812',
    branch: 'Ahmedabad Main Campus',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    attendance: 98.0,
    latestScore: '96/100 (Rank #1)',
    feeStatus: 'All Fees Paid',
    targetExam: 'Science Olympiad (NSO/IMO)',
  },
];

export const mockFeeInvoices = [
  {
    id: 'inv-02',
    title: 'Academic Year 2026-2027: Term 2 Fee (Tuition + Lab + Test Series)',
    amount: 45000,
    dueDate: '25 Aug 2026',
    status: 'unpaid',
    studentName: 'Aarav Sharma',
    breakdown: [
      { head: 'Tuition Fee (JEE Advanced Coaching)', amount: 32000 },
      { head: 'CBT All-India Test Series & Mock Exams', amount: 8000 },
      { head: 'Advanced Physics & Chemistry Lab Consumables', amount: 5000 },
    ],
  },
  {
    id: 'inv-01',
    title: 'Academic Year 2026-2027: Term 1 Fee (Admission & Courseware)',
    amount: 45000,
    dueDate: '10 Apr 2026',
    status: 'paid',
    paidOn: '08 Apr 2026',
    transactionId: 'TXN-RAZOR-99837241',
    receiptUrl: '/receipts/APX-REC-2026-01.pdf',
    studentName: 'Aarav Sharma',
  },
];

export const mockConsentForms = [
  {
    id: 'cnf-01',
    title: 'ISRO Space Application Centre (SAC) Educational Visit',
    date: '15 Sep 2026',
    description: 'Day-long guided excursion for Class 11 JEE students to explore satellite mechanics and astrophysics labs at ISRO Ahmedabad.',
    status: 'pending', // pending, signed, declined
    deadline: '05 Sep 2026',
    category: 'Field Trip',
  },
  {
    id: 'cnf-02',
    title: 'Institutional Social Media & Media Photo/Video Consent',
    description: 'Grant permission for student photographs in academic achievement highlights and exam toppers brochures on official social channels.',
    status: 'signed',
    signedOn: '01 Jun 2026',
    category: 'Child Safety & Photo Consent',
  },
  {
    id: 'cnf-03',
    title: 'Emergency Medical Care & Hospital Authorization',
    description: 'Authorization for campus medical officer to administer first-aid and transport to Apollo Hospital in case of medical emergencies.',
    status: 'signed',
    signedOn: '01 Jun 2026',
    category: 'Medical Authorization',
  },
];

export const mockPTMSlots = [
  {
    id: 'ptm-01',
    teacherName: 'Prof. Amit Verma',
    subject: 'Physics (Mentor)',
    availableSlots: ['Saturday, 10:00 AM', 'Saturday, 10:30 AM', 'Saturday, 11:00 AM'],
    mode: 'In-Person / Video Call',
    status: 'available',
  },
  {
    id: 'ptm-02',
    teacherName: 'Dr. Sunita Rao',
    subject: 'Chemistry',
    availableSlots: ['Saturday, 02:00 PM', 'Saturday, 02:30 PM'],
    mode: 'Video Call',
    status: 'available',
  },
];

export const mockBusLiveTracking = {
  routeNumber: 'Route 14 - Satellite / Bodakdev Express',
  vehicleNumber: 'GJ-01-ED-9042',
  driverName: 'Rameshwar Yadav (+91 98765 00112)',
  currentStop: 'Judges Bungalow Cross Road',
  nextStop: 'Apex Academy Ahmedabad',
  etaMinutes: 12,
  speedKmH: 34,
  status: 'In Transit',
  rfidLogs: [
    { event: 'Morning Boarding (Home Stop)', time: '07:42 AM', location: 'Prahlad Nagar Garden', verified: true },
    { event: 'Morning Campus Arrival', time: '08:15 AM', location: 'Apex Main Gate', verified: true },
  ],
};

export const mockParentAINarrative = {
  studentName: 'Aarav',
  english:
    'Aarav has shown consistent academic improvement from 64% → 68% → 72% across his last three mock tests. His conceptual foundation in Mathematics is particularly commendable (avg 78%). Physics rotational mechanics remains an area of active focus (avg 56%) where additional problem practice is recommended. His attendance stands at a disciplined 94.2%.',
  hindi:
    'आरव ने पिछले तीन मॉक टेस्ट में 64% → 68% → 72% का लगातार सुधार दिखाया है। गणित में उनकी वैचारिक समझ विशेष रूप से मजबूत है (औसत 78%)। भौतिकी में रोटेशनल मोशन पर थोड़ा और अभ्यास आवश्यक है (औसत 56%)। उनकी उपस्थिति अनुशासित 94.2% है।',
};

