-- ============================================================================
-- EduOS Row-Level Security (RLS) Policies
-- ============================================================================

ALTER TABLE public.tenants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.branches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subjects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.timetables ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendances ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.exams ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.exam_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.assignment_submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chart_of_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fee_structures ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fee_invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.journal_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.teachers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employee_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leave_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transport_vehicles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transport_routes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.library_books ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.library_loans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_assets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.compliance_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.smc_minutes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.udise_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.complaint_cases ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inquiry_leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admission_applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.consent_forms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.consent_responses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ptm_bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.support_tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lms_courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lms_lessons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lms_notes ENABLE ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation_on_branches ON public.branches USING (tenant_id = public.current_tenant_id());
CREATE POLICY tenant_isolation_on_user_profiles ON public.user_profiles USING (tenant_id = public.current_tenant_id());
CREATE POLICY tenant_isolation_on_batches ON public.batches USING (tenant_id = public.current_tenant_id());
CREATE POLICY tenant_isolation_on_subjects ON public.subjects USING (tenant_id = public.current_tenant_id());
CREATE POLICY tenant_isolation_on_timetables ON public.timetables USING (tenant_id = public.current_tenant_id());
CREATE POLICY tenant_isolation_on_students ON public.students USING (tenant_id = public.current_tenant_id());
CREATE POLICY tenant_isolation_on_attendances ON public.attendances USING (tenant_id = public.current_tenant_id());
CREATE POLICY tenant_isolation_on_exams ON public.exams USING (tenant_id = public.current_tenant_id());
CREATE POLICY tenant_isolation_on_exam_results ON public.exam_results USING (tenant_id = public.current_tenant_id());
CREATE POLICY tenant_isolation_on_assignments ON public.assignments USING (tenant_id = public.current_tenant_id());
CREATE POLICY tenant_isolation_on_assignment_submissions ON public.assignment_submissions USING (tenant_id = public.current_tenant_id());
CREATE POLICY tenant_isolation_on_chart_of_accounts ON public.chart_of_accounts USING (tenant_id = public.current_tenant_id());
CREATE POLICY tenant_isolation_on_fee_structures ON public.fee_structures USING (tenant_id = public.current_tenant_id());
CREATE POLICY tenant_isolation_on_fee_invoices ON public.fee_invoices USING (tenant_id = public.current_tenant_id());
CREATE POLICY tenant_isolation_on_journal_entries ON public.journal_entries USING (tenant_id = public.current_tenant_id());
CREATE POLICY tenant_isolation_on_teachers ON public.teachers USING (tenant_id = public.current_tenant_id());
CREATE POLICY tenant_isolation_on_employee_records ON public.employee_records USING (tenant_id = public.current_tenant_id());
CREATE POLICY tenant_isolation_on_leave_requests ON public.leave_requests USING (tenant_id = public.current_tenant_id());
CREATE POLICY tenant_isolation_on_transport_vehicles ON public.transport_vehicles USING (tenant_id = public.current_tenant_id());
CREATE POLICY tenant_isolation_on_transport_routes ON public.transport_routes USING (tenant_id = public.current_tenant_id());
CREATE POLICY tenant_isolation_on_library_books ON public.library_books USING (tenant_id = public.current_tenant_id());
CREATE POLICY tenant_isolation_on_library_loans ON public.library_loans USING (tenant_id = public.current_tenant_id());
CREATE POLICY tenant_isolation_on_inventory_assets ON public.inventory_assets USING (tenant_id = public.current_tenant_id());
CREATE POLICY tenant_isolation_on_compliance_documents ON public.compliance_documents USING (tenant_id = public.current_tenant_id());
CREATE POLICY tenant_isolation_on_smc_minutes ON public.smc_minutes USING (tenant_id = public.current_tenant_id());
CREATE POLICY tenant_isolation_on_udise_records ON public.udise_records USING (tenant_id = public.current_tenant_id());
CREATE POLICY tenant_isolation_on_complaint_cases ON public.complaint_cases USING (tenant_id = public.current_tenant_id());
CREATE POLICY tenant_isolation_on_inquiry_leads ON public.inquiry_leads USING (tenant_id = public.current_tenant_id());
CREATE POLICY tenant_isolation_on_admission_applications ON public.admission_applications USING (tenant_id = public.current_tenant_id());
CREATE POLICY tenant_isolation_on_consent_forms ON public.consent_forms USING (tenant_id = public.current_tenant_id());
CREATE POLICY tenant_isolation_on_consent_responses ON public.consent_responses USING (tenant_id = public.current_tenant_id());
CREATE POLICY tenant_isolation_on_ptm_bookings ON public.ptm_bookings USING (tenant_id = public.current_tenant_id());
CREATE POLICY tenant_isolation_on_notices ON public.notices USING (tenant_id = public.current_tenant_id());
CREATE POLICY tenant_isolation_on_support_tickets ON public.support_tickets USING (tenant_id = public.current_tenant_id());
CREATE POLICY tenant_isolation_on_lms_courses ON public.lms_courses USING (tenant_id = public.current_tenant_id());
CREATE POLICY tenant_isolation_on_lms_lessons ON public.lms_lessons USING (tenant_id = public.current_tenant_id());
CREATE POLICY manage_own_lms_notes ON public.lms_notes FOR ALL USING (auth.uid() = user_id OR tenant_id = public.current_tenant_id());

