export const mockCurrentStudent = {
  id: 's-1',
  userId: 'u-1',
  name: 'Aarav Patel',
  email: 'aarav.patel@apex.edu.in',
  rollNumber: 'APEX-JEE-26-004',
  admissionNumber: 'ADM-2025-9912',
  batchId: 'b-1',
  batchName: 'Class 11 - JEE Advanced Alpha',
  targetExam: 'JEE Advanced (IIT)',
  attendancePct: 93.8,
  rankInBatch: 4,
  parentName: 'Rajesh Patel',
  parentPhone: '+91 98765 43210',
  qrCodeId: 'qr-aarav-9912-apex',
  avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=120&h=120',
};

export const mockTimetable = [
  {
    id: 'slot-1',
    dayOfWeek: 1,
    periodNumber: 1,
    startTime: '08:30 AM',
    endTime: '10:00 AM',
    subjectName: 'Physics (Rotational Dynamics)',
    subjectColor: '#06B6D4',
    teacherName: 'Dr. Rajesh Iyer',
    roomNumber: 'Hall 101',
    batchId: 'b-1',
  },
  {
    id: 'slot-2',
    dayOfWeek: 1,
    periodNumber: 2,
    startTime: '10:15 AM',
    endTime: '11:45 AM',
    subjectName: 'Mathematics (Calculus)',
    subjectColor: '#4F46E5',
    teacherName: 'Prof. Amit Verma',
    roomNumber: 'Hall 102',
    batchId: 'b-1',
  },
  {
    id: 'slot-3',
    dayOfWeek: 1,
    periodNumber: 3,
    startTime: '12:00 PM',
    endTime: '01:30 PM',
    subjectName: 'Organic Chemistry',
    subjectColor: '#10B981',
    teacherName: 'Dr. Sunita Rao',
    roomNumber: 'Lab 2',
    batchId: 'b-1',
  },
];

export const mockLeaveRequests = [
  {
    id: 'l-1',
    employeeName: 'Prof. Vikram Roy',
    designation: 'HOD Chemistry',
    leaveType: 'Casual Leave',
    startDate: '2026-08-20',
    endDate: '2026-08-22',
    reason: 'Family wedding / Personal commitment',
    status: 'pending',
    appliedAt: '2026-08-18 10:30 AM',
  },
];
