export const mockCurrentStudent = {
  id: 'std-aarav-01',
  userId: 'user-std-01',
  name: 'Aarav Sharma',
  email: 'aarav.sharma@mpsdelhi.edu.in',
  rollNumber: 'CBSE-10A-04',
  admissionNumber: 'ADM-2025-1004',
  batchId: 'batch-cbse-10a',
  batchName: 'Class 10-A — CBSE Board Champions (Kalam Section)',
  targetExam: 'CBSE 10th Board Exam 2026',
  attendancePct: 94.6,
  rankInBatch: 2,
  parentName: 'Mr. Rajesh & Mrs. Sunita Sharma',
  parentPhone: '+91 98111 22334',
  qrCodeId: 'MPS-CBSE-10A-004-AARAV',
  avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=150&h=150',
};

export const mockTimetable = [
  {
    id: 'slot-1',
    dayOfWeek: 1,
    periodNumber: 1,
    startTime: '08:00 AM',
    endTime: '08:45 AM',
    subjectName: 'Mathematics (Quadratic Equations)',
    subjectColor: '#2563EB',
    teacherName: 'Prof. Amit Verma',
    roomNumber: 'Room 101',
    batchId: 'batch-cbse-10a',
  },
  {
    id: 'slot-2',
    dayOfWeek: 1,
    periodNumber: 2,
    startTime: '08:45 AM',
    endTime: '09:30 AM',
    subjectName: 'Science (Physics: Electricity)',
    subjectColor: '#0D9488',
    teacherName: 'Mrs. Sunita Rao',
    roomNumber: 'Science Lab 1',
    batchId: 'batch-cbse-10a',
  },
  {
    id: 'slot-3',
    dayOfWeek: 1,
    periodNumber: 3,
    startTime: '09:30 AM',
    endTime: '10:15 AM',
    subjectName: 'English (First Flight)',
    subjectColor: '#7C3AED',
    teacherName: 'Mrs. Ananya Sen',
    roomNumber: 'Room 101',
    batchId: 'batch-cbse-10a',
  },
  {
    id: 'slot-4',
    dayOfWeek: 1,
    periodNumber: 4,
    startTime: '10:35 AM',
    endTime: '11:20 AM',
    subjectName: 'Social Science (Federalism & Democracy)',
    subjectColor: '#EA580C',
    teacherName: 'Mr. Rakesh Sharma',
    roomNumber: 'Room 101',
    batchId: 'batch-cbse-10a',
  },
  {
    id: 'slot-5',
    dayOfWeek: 1,
    periodNumber: 5,
    startTime: '11:20 AM',
    endTime: '12:05 PM',
    subjectName: 'Hindi Course A / Sanskrit',
    subjectColor: '#DC2626',
    teacherName: 'Dr. Meenakshi Joshi',
    roomNumber: 'Room 101',
    batchId: 'batch-cbse-10a',
  },
  {
    id: 'slot-6',
    dayOfWeek: 1,
    periodNumber: 6,
    startTime: '12:05 PM',
    endTime: '12:50 PM',
    subjectName: 'Information Technology (Code 402)',
    subjectColor: '#059669',
    teacherName: 'Mr. Sandeep Patil',
    roomNumber: 'IT Lab 2',
    batchId: 'batch-cbse-10a',
  },
];

export const mockLeaveRequests = [
  {
    id: 'leave-1',
    employeeName: 'Prof. Amit Verma',
    designation: 'HOD Mathematics (Class 9 & 10)',
    leaveType: 'Casual Leave',
    startDate: '2026-08-21',
    endDate: '2026-08-22',
    reason: 'Attending CBSE National Pedagogy Workshop at CBSE Regional Office.',
    status: 'pending',
    appliedAt: '2026-08-19 09:30 AM',
  },
  {
    id: 'leave-2',
    employeeName: 'Mrs. Sunita Rao',
    designation: 'HOD Science (Class 10-A Class Teacher)',
    leaveType: 'Medical Leave',
    startDate: '2026-08-14',
    endDate: '2026-08-14',
    reason: 'Routine health checkup / dental consultation.',
    status: 'approved',
    appliedAt: '2026-08-12 11:15 AM',
  },
];
