'use client';

import React, { useState } from 'react';
import { mockParentAINarrative } from '@/lib/mockData';
import { Sparkles, Languages, Volume2, TrendingUp, CheckCircle2, AlertCircle, Download } from 'lucide-react';

export const ParentAIReport: React.FC = () => {
  const [lang, setLang] = useState<'english' | 'hindi'>('english');
  const [isPlayingAudio, setIsPlayingAudio] = useState(false);

  const toggleAudio = () => {
    setIsPlayingAudio(true);
    setTimeout(() => setIsPlayingAudio(false), 4000);
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <div>
          <h2 style={{ fontSize: '1.5rem', fontWeight: 800, display: 'flex', alignItems: 'center', gap: '10px' }}>
            <Sparkles size={24} color="#F59E0B" /> AI Personalized Progress Narrative
          </h2>
          <p style={{ color: 'var(--text-secondary)', fontSize: '0.9rem', marginTop: '4px' }}>
            Personalized narrative progress reviews generated by the EduOS Intelligence Engine
          </p>
        </div>

        <div style={{ display: 'flex', gap: '8px', background: 'rgba(0, 0, 0, 0.4)', padding: '4px', borderRadius: '8px' }}>
          <button
            onClick={() => setLang('english')}
            style={{
              padding: '6px 14px',
              borderRadius: '6px',
              border: 'none',
              cursor: 'pointer',
              fontWeight: lang === 'english' ? 700 : 500,
              background: lang === 'english' ? '#4F46E5' : 'transparent',
              color: lang === 'english' ? '#fff' : 'var(--text-muted)',
              fontSize: '0.82rem',
            }}
          >
            English
          </button>
          <button
            onClick={() => setLang('hindi')}
            style={{
              padding: '6px 14px',
              borderRadius: '6px',
              border: 'none',
              cursor: 'pointer',
              fontWeight: lang === 'hindi' ? 700 : 500,
              background: lang === 'hindi' ? '#4F46E5' : 'transparent',
              color: lang === 'hindi' ? '#fff' : 'var(--text-muted)',
              fontSize: '0.82rem',
            }}
          >
            हिंदी (Hindi)
          </button>
        </div>
      </div>

      <div className="glass-card" style={{ padding: '28px', display: 'flex', flexDirection: 'column', gap: '20px' }}>
        {/* Trajectory Banner */}
        <div style={{
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          background: 'linear-gradient(135deg, rgba(79, 70, 229, 0.15), rgba(245, 158, 11, 0.1))',
          border: '1px solid rgba(79, 70, 229, 0.3)',
          borderRadius: '12px',
          padding: '16px 20px',
        }}>
          <div>
            <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)', fontWeight: 600 }}>3-TEST PERFORMANCE TRAJECTORY</div>
            <div style={{ fontSize: '1.3rem', fontWeight: 800, color: '#fff', marginTop: '2px', display: 'flex', alignItems: 'center', gap: '8px' }}>
              <TrendingUp size={20} color="#10B981" /> 64% → 68% → 72% (+8.0% Net Growth)
            </div>
          </div>
          <button
            onClick={toggleAudio}
            className="btn-secondary"
            style={{ fontSize: '0.82rem', gap: '6px' }}
          >
            <Volume2 size={16} color={isPlayingAudio ? '#10B981' : 'inherit'} />
            {isPlayingAudio ? 'Playing WhatsApp Audio Voice Summary...' : 'Listen to Voice Summary'}
          </button>
        </div>

        {/* Narrative Box */}
        <div style={{
          background: 'rgba(255, 255, 255, 0.03)',
          border: '1px solid var(--border-subtle)',
          borderRadius: '12px',
          padding: '24px',
          fontSize: '1.05rem',
          lineHeight: 1.8,
          color: 'var(--text-primary)',
        }}>
          &ldquo;{mockParentAINarrative[lang]}&rdquo;
        </div>

        {/* Subject Insights Breakdown */}
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
          <div style={{
            background: 'rgba(16, 185, 129, 0.08)',
            border: '1px solid rgba(16, 185, 129, 0.25)',
            borderRadius: '10px',
            padding: '16px',
          }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '6px', color: '#34D399', fontWeight: 700, fontSize: '0.9rem' }}>
              <CheckCircle2 size={16} /> Key Strengths
            </div>
            <p style={{ fontSize: '0.84rem', color: 'var(--text-secondary)', marginTop: '6px', lineHeight: 1.5 }}>
              Calculus conceptual derivation, Inorganic Chemistry memory retention, consistent daily homework submission.
            </p>
          </div>

          <div style={{
            background: 'rgba(245, 158, 11, 0.08)',
            border: '1px solid rgba(245, 158, 11, 0.25)',
            borderRadius: '10px',
            padding: '16px',
          }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '6px', color: '#FBBF24', fontWeight: 700, fontSize: '0.9rem' }}>
              <AlertCircle size={16} /> Recommended Focus Area
            </div>
            <p style={{ fontSize: '0.84rem', color: 'var(--text-secondary)', marginTop: '6px', lineHeight: 1.5 }}>
              Physics application calculation speed under exam timed pressure (Moments of Inertia integration).
            </p>
          </div>
        </div>

        <div style={{ display: 'flex', justifyContent: 'flex-end', marginTop: '6px' }}>
          <button className="btn-primary" style={{ fontSize: '0.85rem' }}>
            <Download size={16} /> Download Comprehensive Term Report Card (PDF)
          </button>
        </div>
      </div>
    </div>
  );
};
