'use client';

import React, { useState } from 'react';
import { mockParentAINarrative } from '@/lib/mockData';
import { Card, SectionCard, StatCard, Badge, PageHeader, cn } from '@/components/ui';
import { toast } from '@/components/ui/toast';
import {
  Sparkles,
  TrendingUp,
  CheckCircle2,
  AlertCircle,
  Download,
  MessageCircle,
  CalendarCheck,
} from 'lucide-react';

type Lang = 'english' | 'hindi';

export const ParentAIReport: React.FC = () => {
  const [lang, setLang] = useState<Lang>('english');
  const narrative = mockParentAINarrative;

  const handleDownloadPdf = () => {
    toast('Report generating', 'info', `${narrative.studentName}'s term report card · PDF will download shortly`);
  };

  const handleWhatsAppVoice = () => {
    toast('Voice summary sent', 'success', `${lang === 'english' ? 'English' : 'Hindi'} audio summary dispatched to your WhatsApp`);
  };

  return (
    <div className="flex flex-col gap-6">
      <PageHeader
        title="AI progress narrative"
        subtitle={
          <>
            Personalized review for <span className="font-semibold text-foreground">{narrative.studentName} Sharma</span>, generated by the EduOS Intelligence Engine
          </>
        }
        actions={
          <div className="inline-flex items-center gap-1 rounded-md border border-border bg-surface p-1 shadow-xs">
            {(['english', 'hindi'] as Lang[]).map((l) => (
              <button
                key={l}
                onClick={() => setLang(l)}
                className={cn(
                  'rounded-[6px] px-3 py-1.5 text-meta transition-colors',
                  lang === l ? 'bg-primary-soft font-semibold text-primary' : 'font-medium text-text-secondary hover:bg-muted',
                )}
                aria-pressed={lang === l}
              >
                {l === 'english' ? 'English' : 'हिंदी'}
              </button>
            ))}
          </div>
        }
      />

      {/* Supporting metric tiles */}
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <StatCard label="Mock trajectory" value="72%" icon={<TrendingUp size={16} />} tone="success" trend={{ value: '+8.0%', direction: 'up' }} hint="64% → 68% → 72%" />
        <StatCard label="Mathematics avg" value="78%" icon={<CheckCircle2 size={16} />} tone="primary" hint="Strongest subject" />
        <StatCard label="Physics (rotational)" value="56%" icon={<AlertCircle size={16} />} tone="warning" hint="Active focus area" />
        <StatCard label="Attendance" value="94.2%" icon={<CalendarCheck size={16} />} tone="info" hint="Disciplined & consistent" />
      </div>

      <SectionCard
        title="Personalized narrative"
        icon={<Sparkles size={18} />}
        action={<Badge tone="primary">{lang === 'english' ? 'English' : 'हिंदी'}</Badge>}
      >
        <div className="flex flex-col gap-5">
          {/* Trajectory banner */}
          <div className="flex flex-col gap-3 rounded-lg border border-primary/15 bg-primary-soft p-4 sm:flex-row sm:items-center sm:justify-between">
            <div>
              <div className="eyebrow">3-test performance trajectory</div>
              <div className="mt-1 inline-flex items-center gap-2 text-lg font-semibold text-foreground">
                <TrendingUp size={18} className="text-success" /> 64% → 68% → 72%
                <span className="text-success">(+8.0%)</span>
              </div>
            </div>
          </div>

          {/* Narrative text */}
          <blockquote className="rounded-lg border border-border bg-surface-muted p-5 text-body leading-relaxed text-text-secondary">
            &ldquo;{narrative[lang]}&rdquo;
          </blockquote>

          {/* Strengths / focus */}
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
            <div className="rounded-md border border-success/20 bg-success-soft p-4">
              <div className="inline-flex items-center gap-1.5 text-meta font-semibold text-success-foreground">
                <CheckCircle2 size={15} /> Key strengths
              </div>
              <p className="mt-1.5 text-meta leading-relaxed text-text-secondary">
                Calculus conceptual derivation, inorganic chemistry retention, and consistent daily homework submission.
              </p>
            </div>
            <div className="rounded-md border border-warning/20 bg-warning-soft p-4">
              <div className="inline-flex items-center gap-1.5 text-meta font-semibold text-warning-foreground">
                <AlertCircle size={15} /> Recommended focus
              </div>
              <p className="mt-1.5 text-meta leading-relaxed text-text-secondary">
                Physics application calculation speed under timed pressure (moment-of-inertia integration).
              </p>
            </div>
          </div>

          <div className="flex flex-wrap justify-end gap-2">
            <button onClick={handleWhatsAppVoice} className="btn-secondary">
              <MessageCircle size={16} /> Get WhatsApp voice summary
            </button>
            <button onClick={handleDownloadPdf} className="btn-primary">
              <Download size={16} /> Download PDF
            </button>
          </div>
        </div>
      </SectionCard>
    </div>
  );
};
