import {
  UserProfile,
  Tenant,
  Batch,
  Student,
  TimetableSlot,
  AttendanceRecord,
  LMSLesson,
  Assignment,
  ExamResult,
  LeaveRequest,
  Notice,
} from './types';

export const mockTenant: Tenant = {
  id: 'tenant-cbse-dps-01',
  name: 'Modern Public School (CBSE Affiliated)',
  subdomain: 'mps',
  institutionType: 'school',
  primaryColor: '#2563EB', // Royal Blue
  secondaryColor: '#0D9488', // Teal
  accentColor: '#F59E0B', // Amber
  tagline: 'Excellence in CBSE Academics, Values & Innovation (Affiliation No. 1030492)',
  logoUrl: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=120&auto=format&fit=crop&q=80',
};

export const mockProfiles: Record<string, UserProfile> = {
  student: {
    id: 'user-std-01',
    email: 'aarav.sharma@mpsdelhi.edu.in',
    firstName: 'Aarav',
    lastName: 'Sharma',
    role: 'student',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    phone: '+91 98765 43210',
    tenantId: mockTenant.id,
    branchId: 'branch-main-campus',
  },
  teacher: {
    id: 'user-tch-01',
    email: 'amit.verma@mpsdelhi.edu.in',
    firstName: 'Prof. Amit',
    lastName: 'Verma',
    role: 'teacher',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    phone: '+91 98234 56789',
    tenantId: mockTenant.id,
    branchId: 'branch-main-campus',
  },
  principal: {
    id: 'user-prn-01',
    email: 'principal.iyer@mpsdelhi.edu.in',
    firstName: 'Dr. Rajesh',
    lastName: 'Iyer',
    role: 'principal',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    phone: '+91 99887 66554',
    tenantId: mockTenant.id,
    branchId: 'branch-main-campus',
  },
  parent: {
    id: 'user-par-01',
    email: 'rajesh.sharma.parent@gmail.com',
    firstName: 'Mr. Rajesh',
    lastName: 'Sharma',
    role: 'parent',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    phone: '+91 98111 22334',
    tenantId: mockTenant.id,
    branchId: 'branch-main-campus',
  },
  super_admin: {
    id: 'user-adm-01',
    email: 'admin@eduos.app',
    firstName: 'EduOS',
    lastName: 'SuperAdmin',
    role: 'super_admin',
    avatarUrl: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=80',
    phone: '+91 90000 00001',
    tenantId: mockTenant.id,
  },
};

export const mockBatches: Batch[] = [
  {
    id: 'batch-cbse-10a',
    name: 'Class 10-A — CBSE Board Champions (Kalam Section)',
    code: 'CBSE-10A',
    targetExam: 'CBSE 10th Board Exam 2026',
    gradeLevel: 'Class 10',
    roomNumber: 'Room 101',
    mentorTeacherName: 'Mrs. Sunita Rao (Science HOD)',
    studentCount: 38,
    capacity: 40,
  },
  {
    id: 'batch-cbse-10b',
    name: 'Class 10-B — CBSE Achievers (Aryabhata Section)',
    code: 'CBSE-10B',
    targetExam: 'CBSE 10th Board Exam 2026',
    gradeLevel: 'Class 10',
    roomNumber: 'Room 102',
    mentorTeacherName: 'Prof. Amit Verma (Maths HOD)',
    studentCount: 40,
    capacity: 40,
  },
  {
    id: 'batch-cbse-9a',
    name: 'Class 9-A — CBSE Foundation (Ramanujan Section)',
    code: 'CBSE-9A',
    targetExam: 'CBSE Class 9 Annual Exam',
    gradeLevel: 'Class 9',
    roomNumber: 'Room 201',
    mentorTeacherName: 'Dr. Rajesh Iyer (Mathematics)',
    studentCount: 36,
    capacity: 40,
  },
  {
    id: 'batch-cbse-9b',
    name: 'Class 9-B — CBSE Scholars (Bose Section)',
    code: 'CBSE-9B',
    targetExam: 'CBSE Class 9 Annual Exam',
    gradeLevel: 'Class 9',
    roomNumber: 'Room 202',
    mentorTeacherName: 'Mrs. Ananya Sen (English)',
    studentCount: 35,
    capacity: 40,
  },
];

export const mockCurrentStudent: Student = {
  id: 'std-aarav-01',
  userId: 'user-std-01',
  name: 'Aarav Sharma',
  email: 'aarav.sharma@mpsdelhi.edu.in',
  rollNumber: 'CBSE-10A-04',
  admissionNumber: 'ADM-2025-1004',
  batchId: 'batch-cbse-10a',
  batchName: 'Class 10-A — CBSE Board Champions (Kalam Section)',
  targetExam: 'CBSE 10th Board Exam 2026',
  attendancePct: 94.6,
  rankInBatch: 2,
  parentName: 'Mr. Rajesh & Mrs. Sunita Sharma',
  parentPhone: '+91 98111 22334',
  qrCodeId: 'MPS-CBSE-10A-004-AARAV',
  avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
};

export const mockStudentsInBatch: Student[] = [
  mockCurrentStudent,
  {
    id: 'std-02',
    userId: 'user-std-02',
    name: 'Ananya Gupta',
    email: 'ananya.gupta@mpsdelhi.edu.in',
    rollNumber: 'CBSE-10A-01',
    admissionNumber: 'ADM-2025-1001',
    batchId: 'batch-cbse-10a',
    batchName: 'Class 10-A — CBSE Board Champions (Kalam Section)',
    targetExam: 'CBSE 10th Board Exam 2026',
    attendancePct: 97.3,
    rankInBatch: 1,
    parentName: 'Mr. Sanjay Gupta',
    parentPhone: '+91 98222 33445',
    qrCodeId: 'MPS-CBSE-10A-001-ANANYA',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'std-03',
    userId: 'user-std-03',
    name: 'Rohan Mehra',
    email: 'rohan.mehra@mpsdelhi.edu.in',
    rollNumber: 'CBSE-10A-07',
    admissionNumber: 'ADM-2025-1007',
    batchId: 'batch-cbse-10a',
    batchName: 'Class 10-A — CBSE Board Champions (Kalam Section)',
    targetExam: 'CBSE 10th Board Exam 2026',
    attendancePct: 89.5,
    rankInBatch: 4,
    parentName: 'Dr. Vivek Mehra',
    parentPhone: '+91 98333 44556',
    qrCodeId: 'MPS-CBSE-10A-007-ROHAN',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'std-04',
    userId: 'user-std-04',
    name: 'Pooja Verma',
    email: 'pooja.verma@mpsdelhi.edu.in',
    rollNumber: 'CBSE-10A-11',
    admissionNumber: 'ADM-2025-1011',
    batchId: 'batch-cbse-10a',
    batchName: 'Class 10-A — CBSE Board Champions (Kalam Section)',
    targetExam: 'CBSE 10th Board Exam 2026',
    attendancePct: 78.4,
    rankInBatch: 12,
    parentName: 'Mr. Alok Verma',
    parentPhone: '+91 98444 55667',
    qrCodeId: 'MPS-CBSE-10A-011-POOJA',
    avatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'std-05',
    userId: 'user-std-05',
    name: 'Kavya Nair',
    email: 'kavya.nair@mpsdelhi.edu.in',
    rollNumber: 'CBSE-10A-15',
    admissionNumber: 'ADM-2025-1015',
    batchId: 'batch-cbse-10a',
    batchName: 'Class 10-A — CBSE Board Champions (Kalam Section)',
    targetExam: 'CBSE 10th Board Exam 2026',
    attendancePct: 92.8,
    rankInBatch: 3,
    parentName: 'Mrs. Radhika Nair',
    parentPhone: '+91 98555 66778',
    qrCodeId: 'MPS-CBSE-10A-015-KAVYA',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
  },
];

export const mockTimetable: TimetableSlot[] = [
  {
    id: 'slot-1',
    dayOfWeek: 1,
    periodNumber: 1,
    startTime: '08:00 AM',
    endTime: '08:45 AM',
    subjectName: 'Mathematics (Quadratic Equations)',
    subjectColor: '#2563EB',
    teacherName: 'Prof. Amit Verma',
    roomNumber: 'Room 101',
    batchId: 'batch-cbse-10a',
  },
  {
    id: 'slot-2',
    dayOfWeek: 1,
    periodNumber: 2,
    startTime: '08:45 AM',
    endTime: '09:30 AM',
    subjectName: 'Science (Physics: Electricity)',
    subjectColor: '#0D9488',
    teacherName: 'Mrs. Sunita Rao',
    roomNumber: 'Science Lab 1',
    batchId: 'batch-cbse-10a',
  },
  {
    id: 'slot-3',
    dayOfWeek: 1,
    periodNumber: 3,
    startTime: '09:30 AM',
    endTime: '10:15 AM',
    subjectName: 'English (First Flight)',
    subjectColor: '#7C3AED',
    teacherName: 'Mrs. Ananya Sen',
    roomNumber: 'Room 101',
    batchId: 'batch-cbse-10a',
  },
  {
    id: 'slot-4',
    dayOfWeek: 1,
    periodNumber: 4,
    startTime: '10:35 AM',
    endTime: '11:20 AM',
    subjectName: 'Social Science (Federalism & Democracy)',
    subjectColor: '#EA580C',
    teacherName: 'Mr. Rakesh Sharma',
    roomNumber: 'Room 101',
    batchId: 'batch-cbse-10a',
  },
  {
    id: 'slot-5',
    dayOfWeek: 1,
    periodNumber: 5,
    startTime: '11:20 AM',
    endTime: '12:05 PM',
    subjectName: 'Hindi Course A / Sanskrit',
    subjectColor: '#DC2626',
    teacherName: 'Dr. Meenakshi Joshi',
    roomNumber: 'Room 101',
    batchId: 'batch-cbse-10a',
  },
  {
    id: 'slot-6',
    dayOfWeek: 1,
    periodNumber: 6,
    startTime: '12:05 PM',
    endTime: '12:50 PM',
    subjectName: 'Information Technology (Code 402)',
    subjectColor: '#059669',
    teacherName: 'Mr. Sandeep Patil',
    roomNumber: 'IT Lab 2',
    batchId: 'batch-cbse-10a',
  },
];

export const mockSubjects = [
  { id: 'sub-1', name: 'Mathematics (Code 041)', code: 'MATH-041', color: '#2563EB', icon: 'Calculator' },
  { id: 'sub-2', name: 'Science (Physics, Chem, Bio - Code 086)', code: 'SCI-086', color: '#0D9488', icon: 'Atom' },
  { id: 'sub-3', name: 'Social Science (Hist, Civics, Geo, Eco - Code 087)', code: 'SST-087', color: '#EA580C', icon: 'Globe' },
  { id: 'sub-4', name: 'English Language & Literature (Code 184)', code: 'ENG-184', color: '#7C3AED', icon: 'BookOpen' },
  { id: 'sub-5', name: 'Hindi Course A (Code 002)', code: 'HIN-002', color: '#DC2626', icon: 'Languages' },
  { id: 'sub-6', name: 'Information Technology / AI (Code 402)', code: 'IT-402', color: '#059669', icon: 'Cpu' },
];

export const mockAttendanceHistory: AttendanceRecord[] = [
  { id: 'att-1', date: '2026-08-18', status: 'present', remarks: 'Present in all 8 periods' },
  { id: 'att-2', date: '2026-08-17', status: 'present', remarks: 'Present in all 8 periods' },
  { id: 'att-3', date: '2026-08-14', status: 'present', remarks: 'Present in all 8 periods' },
  { id: 'att-4', date: '2026-08-13', status: 'late', remarks: 'Bus delay: 15 mins late check-in' },
  { id: 'att-5', date: '2026-08-12', status: 'present', remarks: 'Present in all 8 periods' },
  { id: 'att-6', date: '2026-08-11', status: 'present', remarks: 'Present in all 8 periods' },
  { id: 'att-7', date: '2026-08-08', status: 'absent', remarks: 'Sick leave (Medical slip submitted)' },
];

export const mockLMSLessons: LMSLesson[] = [
  {
    id: 'lms-1',
    subject: 'Mathematics',
    chapterTitle: 'Chapter 4: Quadratic Equations',
    lessonTitle: 'Mastering the Quadratic Formula & Nature of Roots (Discriminant)',
    durationMinutes: 45,
    contentType: 'video',
    contentUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    completed: true,
  },
  {
    id: 'lms-2',
    subject: 'Science (Physics)',
    chapterTitle: 'Chapter 12: Electricity',
    lessonTitle: "Verification of Ohm's Law, Resistance in Series and Parallel Combinations",
    durationMinutes: 50,
    contentType: 'pdf',
    contentUrl: '/sample-notes.pdf',
    completed: true,
  },
  {
    id: 'lms-3',
    subject: 'Science (Chemistry)',
    chapterTitle: 'Chapter 1: Chemical Reactions & Equations',
    lessonTitle: 'Balancing Chemical Equations & Redox Reactions with NCERT Exemplar',
    durationMinutes: 40,
    contentType: 'video',
    contentUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    completed: false,
  },
  {
    id: 'lms-4',
    subject: 'Social Science',
    chapterTitle: 'Chapter 2: Nationalism in India',
    lessonTitle: 'Non-Cooperation Movement, Dandi Salt March & Timeline Mind-Map',
    durationMinutes: 35,
    contentType: 'notes',
    contentUrl: '/sample-notes.pdf',
    completed: false,
  },
];

export const mockAssignments: Assignment[] = [
  {
    id: 'asg-1',
    subject: 'Mathematics',
    title: 'NCERT Chapter 4 - Quadratic Equations Exercise 4.2 & 4.3',
    dueDate: '2026-08-22',
    maxMarks: 25,
    status: 'submitted',
    obtainedMarks: 23,
    feedback: 'Good work using the quadratic formula. Watch out for sign errors when finding discriminant in Q7.',
  },
  {
    id: 'asg-2',
    subject: 'Science (Physics)',
    title: "Science Lab Practical File - Ohm's Law & Circuit Diagram Verification",
    dueDate: '2026-08-25',
    maxMarks: 20,
    status: 'pending',
  },
  {
    id: 'asg-3',
    subject: 'Social Science',
    title: 'Map Skill Worksheet - Major Iron & Steel Plants & Soil Types of India',
    dueDate: '2026-08-20',
    maxMarks: 15,
    status: 'submitted',
    obtainedMarks: 15,
    feedback: 'Excellent precise map plotting and labelling.',
  },
  {
    id: 'asg-4',
    subject: 'English',
    title: 'Formal Letter Writing Practice: Letter to Editor on Road Safety',
    dueDate: '2026-08-27',
    maxMarks: 10,
    status: 'pending',
  },
];

export const mockExamResults: ExamResult[] = [
  {
    id: 'res-1',
    examTitle: 'CBSE Pre-Board Examination 1 (Mathematics Standard - Code 041)',
    subject: 'Mathematics',
    examDate: '2026-08-10',
    totalMarks: 80,
    marksObtained: 74,
    percentile: 96.8,
    rankInBatch: 2,
    mistakeSummary: 'Lost 4 marks in Trigonometric Identities proving question (Section D). 2 minor calculation errors in Surface Area & Volumes.',
    weakTopics: ['Trigonometric Identities (Section D Proving)', 'Surface Areas and Volumes - Combination of Solids'],
  },
  {
    id: 'res-2',
    examTitle: 'CBSE Periodic Assessment 2 (PA-2 - Science PCB)',
    subject: 'Science',
    examDate: '2026-07-28',
    totalMarks: 40,
    marksObtained: 38,
    percentile: 98.2,
    rankInBatch: 1,
    mistakeSummary: '1 mark lost in Ray diagram precision for Concave mirror between F and C.',
    weakTopics: ['Ray Optics Diagrams precision', 'Excretory System Nephron labeling'],
  },
  {
    id: 'res-3',
    examTitle: 'CBSE Periodic Assessment 1 (PA-1 - Social Science)',
    subject: 'Social Science',
    examDate: '2026-06-20',
    totalMarks: 40,
    marksObtained: 36,
    percentile: 94.0,
    rankInBatch: 3,
    mistakeSummary: '2 marks lost in 5-marker question on Federalism power sharing features.',
    weakTopics: ['Decentralization in India 1992 Amendment provisions'],
  },
];

export const mockLeaveRequests: LeaveRequest[] = [
  {
    id: 'leave-1',
    employeeName: 'Prof. Amit Verma',
    designation: 'HOD Mathematics (Class 9 & 10)',
    leaveType: 'Casual Leave',
    startDate: '2026-08-21',
    endDate: '2026-08-22',
    reason: 'Attending CBSE National Pedagogy Workshop at CBSE Regional Office.',
    status: 'pending',
    appliedAt: '2026-08-19 09:30 AM',
  },
  {
    id: 'leave-2',
    employeeName: 'Mrs. Sunita Rao',
    designation: 'HOD Science (Class 10-A Class Teacher)',
    leaveType: 'Medical Leave',
    startDate: '2026-08-14',
    endDate: '2026-08-14',
    reason: 'Routine health checkup / dental consultation.',
    status: 'approved',
    appliedAt: '2026-08-12 11:15 AM',
  },
];

export const mockNotices: Notice[] = [
  {
    id: 'not-1',
    title: 'CBSE Circular: Final Verification of Candidate List (LOC) for Class 10 Board 2026',
    content: 'All parents and students of Class 10 are requested to verify spelling of candidate name, date of birth, mother/father name as per Aadhaar & Birth certificate in the school portal by 25th August.',
    category: 'urgent',
    priority: 'urgent',
    author: "Principal's Office & CBSE Examination Cell",
    date: '19 Aug 2026',
    targetRole: 'all',
  },
  {
    id: 'not-2',
    title: 'Schedule for CBSE Pre-Board 1 & Internal Assessment Viva (Class 9 & 10)',
    content: 'Pre-Board Examination 1 will commence from 15th September 2026. Detailed date sheet, syllabus weightage, and practical lab schedule have been uploaded on the student portal.',
    category: 'exam',
    priority: 'urgent',
    author: 'Academic Directorate',
    date: '17 Aug 2026',
    targetRole: 'student',
  },
  {
    id: 'not-3',
    title: 'Mandatory Term-1 Parent-Teacher Meeting (PTM) on Saturday',
    content: 'Term 1 PTM for Class 9 and Class 10 is scheduled for Saturday, 23rd August from 10:00 AM to 01:30 PM. Book your 1-on-1 slot via the Parent Portal.',
    category: 'academic',
    priority: 'normal',
    author: 'Academic Coordination Committee',
    date: '15 Aug 2026',
    targetRole: 'parent',
  },
  {
    id: 'not-4',
    title: 'CBSE Regional Science & Innovation Fair 2026: Team Registrations',
    content: 'Students from Class 9 & 10 interested in submitting science models or IoT innovation projects must submit synopsis to the Science Lab by Friday.',
    category: 'event',
    priority: 'normal',
    author: 'Science & Robotics Club',
    date: '12 Aug 2026',
    targetRole: 'all',
  },
];

export const mockPTMSlots = [
  {
    id: 'ptm-1',
    teacherName: 'Prof. Amit Verma (Maths HOD)',
    subject: 'Mathematics Standard (Class 10)',
    date: '2026-08-23',
    time: '10:15 AM – 10:30 AM',
    status: 'confirmed',
    room: 'Room 101 / Google Meet',
  },
  {
    id: 'ptm-2',
    teacherName: 'Mrs. Sunita Rao (Class Teacher & Science HOD)',
    subject: 'Science & Class Conduct (Class 10-A)',
    date: '2026-08-23',
    time: '10:45 AM – 11:00 AM',
    status: 'pending',
    room: 'Science Lab 1',
  },
];

export const mockFeesBreakdown = {
  totalAnnualFee: 78000,
  paidAmount: 52000,
  pendingAmount: 26000,
  dueDate: '2026-09-15',
  items: [
    { name: 'Tuition Fee (Term 2 - Class 10)', amount: 18000, status: 'pending' },
    { name: 'CBSE Board Examination & Registration Fee', amount: 3200, status: 'pending' },
    { name: 'Composite Science & Computer Lab Fee', amount: 4800, status: 'pending' },
    { name: 'Tuition Fee (Term 1 - Class 10)', amount: 18000, status: 'paid' },
    { name: 'Annual Development & Smart Class Charge', amount: 34000, status: 'paid' },
  ],
};

export const mockBusLiveTracking = {
  routeNumber: 'Route 14 — West Delhi Express',
  vehicleNumber: 'DL-1PB-4912',
  driverName: 'Mr. Jagdish Singh',
  driverPhone: '+91 98999 12345',
  attendantName: 'Mrs. Shanti Devi',
  currentSpeedKmph: 32,
  speedKmH: 32,
  currentStop: 'Janakpuri District Centre',
  nextStop: 'Modern Public School Main Gate',
  etaMinutes: 8,
  latitude: 28.6289,
  longitude: 77.0815,
  status: 'en_route',
  rfidLogs: [
    { event: 'Boarded bus at morning stop', location: 'Janakpuri Gate 2', time: '07:22 AM', verified: true },
    { event: 'Passed GPS Geo-fence #3', location: 'Ring Road Crossing', time: '07:38 AM', verified: true },
    { event: 'De-boarded at school gate', location: 'Main Senior Wing Gate', time: '07:50 AM', verified: true },
  ],
};

export const mockConsentForms = [
  {
    id: 'consent-1',
    title: 'Consent for CBSE Science Exhibition Field Visit to National Science Centre',
    date: '2026-08-28',
    deadline: '2026-08-27',
    signedOn: 'Yesterday, 04:15 PM',
    category: 'Excursion & Field Visit',
    status: 'signed',
    description: 'Educational field visit for Class 10 science students. Includes guided workshop on Optics & Robotics.',
  },
  {
    id: 'consent-2',
    title: 'Consent for After-School Pre-Board Remedial & Doubts Classes (3:00 PM to 4:30 PM)',
    date: '2026-09-01',
    deadline: '2026-08-30',
    category: 'Academic Remedial',
    status: 'pending',
    description: 'Targeted revision sessions for Mathematics & Science board preparation.',
  },
];

export const mockMedicalRecord = {
  bloodGroup: 'B+',
  allergies: ['Dust / Pollen (Mild)'],
  emergencyContact1: 'Mr. Rajesh Sharma (Father) - +91 98111 22334',
  emergencyContact2: 'Mrs. Sunita Sharma (Mother) - +91 98111 55667',
  doctorName: 'Dr. A. K. Banerjee (Pediatrician)',
  doctorPhone: '+91 98100 99887',
  specialInstructions: 'Inhaler available in school infirmary locker #14 if shortness of breath occurs during sports.',
};

export const mockAIQuestions = [
  {
    id: 'q-1',
    topic: 'Quadratic Equations (NCERT Class 10)',
    question: 'Find the nature of the roots of the quadratic equation 2x² - 6x + 3 = 0. If real roots exist, find them using the quadratic formula.',
    difficulty: 'Medium',
    type: 'Subjective (3 Marks)',
    source: 'CBSE Board 2024 Past Paper',
  },
  {
    id: 'q-2',
    topic: 'Electricity (NCERT Class 10)',
    question: 'An electric lamp of resistance 20 Ω and a conductor of 4 Ω resistance are connected in series to a 6 V battery. Calculate: (a) Total resistance of the circuit, (b) The current flowing through the circuit.',
    difficulty: 'Medium',
    type: 'Numerical (3 Marks)',
    source: 'NCERT In-Text Exemplar',
  },
  {
    id: 'q-3',
    topic: 'Life Processes (NCERT Class 10)',
    question: 'Describe with a neat diagram the double circulation of blood in human beings. Why is it necessary to separate oxygenated and deoxygenated blood in mammals and birds?',
    difficulty: 'Hard',
    type: 'Long Answer (5 Marks)',
    source: 'CBSE Sample Paper 2025-26',
  },
];

export const mockStatutoryStandards = [
  {
    id: 'std-cbse-aff',
    code: 'CBSE-AFF-2026',
    title: 'CBSE Affiliation Bye-Laws 2018 (Composite Secondary Renewal)',
    authority: 'Central Board of Secondary Education (CBSE)',
    jurisdiction: 'National',
    frequency: 'Every 5 Years',
    mandatoryDocuments: ['Building Safety Certificate', 'Fire Safety NOC', 'Sanitation Certificate', 'Staff Salary Bank ECS Proof'],
    status: 'compliant',
    validUntil: '2028-03-31',
  },
  {
    id: 'std-pocso',
    code: 'POCSO-ACT-2012',
    title: 'POCSO & Child Safety Internal Grievance Committee',
    authority: 'Ministry of Women and Child Development (Govt. of India)',
    jurisdiction: 'National',
    frequency: 'Continuous / Annual Audit',
    mandatoryDocuments: ['CCTV Coverage Log in all corridors/entrances', 'Police Verification of All Non-Teaching Staff', 'POCSO Box Register'],
    status: 'compliant',
    validUntil: '2027-01-01',
  },
  {
    id: 'std-fire',
    code: 'FIRE-SAFETY-NOC',
    title: 'State Fire Service Department NOC & Extinguisher Hydrotest Log',
    authority: 'Delhi Fire Services (Govt. of NCT of Delhi)',
    jurisdiction: 'State',
    frequency: 'Annual',
    mandatoryDocuments: ['Fire NOC Certificate', 'Evacuation Drill Log Book', 'Hydrant Pressure Test Report'],
    status: 'compliant',
    validUntil: '2027-04-30',
  },
  {
    id: 'std-udise',
    code: 'UDISE-PLUS-RETURN',
    title: 'Unified District Information System for Education (UDISE+ Annual Return)',
    authority: 'Ministry of Education (Govt. of India)',
    jurisdiction: 'National',
    frequency: 'Annual (By 30th November)',
    mandatoryDocuments: ['Student Aadhar Verification Log', 'Infrastructure & Toilet Ratio Report', 'Teacher Academic Profile Form'],
    status: 'action_required',
    validUntil: '2026-11-30',
  },
];

export const mockParentChildren = [
  {
    id: 'child-1',
    name: 'Aarav Sharma',
    rollNumber: 'CBSE-10A-04',
    batchName: 'Class 10-A — CBSE Board Champions (Kalam Section)',
    targetExam: 'CBSE 10th Board Exam 2026',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    attendancePct: 94.6,
    rankInBatch: 2,
    unreadAlerts: 1,
  },
  {
    id: 'child-2',
    name: 'Ananya Sharma',
    rollNumber: 'CBSE-9A-02',
    batchName: 'Class 9-A — CBSE Foundation (Ramanujan Section)',
    targetExam: 'CBSE Class 9 Annual Exam',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    attendancePct: 96.2,
    rankInBatch: 1,
    unreadAlerts: 0,
  },
];

export const mockParentAINarrative = {
  studentName: 'Aarav',
  english:
    'Aarav continues to demonstrate outstanding consistency in CBSE Class 10 preparation. He ranks #2 in Section 10-A with a cumulative score of 93.8% across Periodic Assessments and Pre-Board 1. His strongest areas are Mathematics Quadratic Equations and Physics Electricity, with a recommended focus on Trigonometric Identities proving questions.',
  hindi:
    'आरव ने सीबीएसई कक्षा 10 की परीक्षाओं में निरंतर प्रगति और उत्कृष्ट प्रदर्शन बनाए रखा है। वह 93.8% अंकों के साथ अपनी कक्षा 10-ए में दूसरे स्थान पर हैं। गणित और विज्ञान में उनका प्रदर्शन असाधारण है।',
  executiveSummary:
    'Aarav continues to demonstrate outstanding consistency in CBSE Class 10 preparation. He ranks #2 in Section 10-A with a cumulative score of 93.8% across Periodic Assessments and Pre-Board 1.',
  keyStrengths: [
    'Mastery in Mathematics (Quadratic Equations, Coordinate Geometry) with 96.8 percentile.',
    'Consistent 95%+ lab practical performance in Physics & Chemistry experiments.',
    'Punctual attendance record (94.6% presence, only 1 excused medical leave).',
  ],
  recommendedFocusAreas: [
    'Trigonometric Identities proving problems in Section D (lost 4 marks in Pre-Board 1).',
    'Excretory system & Nephron ray diagram labelling speed in Science Biology.',
    'Map work practice for Social Science geography unit.',
  ],
  teacherObservations:
    'Mrs. Sunita Rao notes that Aarav is highly attentive during class problem-solving and actively helps peers in group study sessions.',
  nextMilestone: 'CBSE Pre-Board Examination 2 starting 15th November 2026.',
};

export const mockFeeInvoices = [
  {
    id: 'inv-101',
    invoiceNumber: 'INV-2026-TERM2-1004',
    title: 'Term 2 Composite Tuition & CBSE Board Exam Fee',
    dueDate: '2026-09-15',
    amount: 26000,
    status: 'pending',
    breakdown: [
      { item: 'Tuition Fee (Term 2 - Class 10)', amount: 18000 },
      { item: 'CBSE Board Examination & Registration Fee', amount: 3200 },
      { item: 'Science & Computer Lab Composite Fee', amount: 4800 },
    ],
  },
  {
    id: 'inv-100',
    invoiceNumber: 'INV-2026-TERM1-1004',
    title: 'Term 1 Tuition & Annual Development Charge',
    dueDate: '2026-04-10',
    paidDate: '2026-04-05',
    amount: 52000,
    status: 'paid',
    receiptUrl: '/sample-receipt.pdf',
    breakdown: [
      { item: 'Tuition Fee (Term 1 - Class 10)', amount: 18000 },
      { item: 'Annual Development & Smart Class Charge', amount: 34000 },
    ],
  },
];

